package com.earthpol.economyPol.economy.model;

public enum PlayerNotificationType {
    INCOMING_OVERFLOW_TO_CUSTODIAL,
    CUSTODIAL_WITHDRAWAL_RETAINED,
    WALLET_OVERFLOW_TO_CUSTODIAL,
    CUSTODIAL_BALANCE_REMINDER,
    OFFLINE_CREDIT_TO_CUSTODIAL,
    CHANGE_ROUTED_TO_CUSTODIAL,
    NOT_ENOUGH_ROOM_FOR_CHANGE
}
